#!/bin/sh
#
# Copies Open Enclave TA's from host's build directory.
#

case "$1" in
    start)
	echo Trying to copy host TAs...
        mkdir /mnt/host
	mount -t 9p -o trans=virtio sh0 /mnt/host -oversion=9p2000.L
	cp /mnt/host/bin/*.ta /lib/optee_armtz
        ;;
esac
